apiVersion: apps/v1
kind: Deployment
metadata:
  name: fibonacci
spec:
  selector:
    matchLabels:
      app: fibonacci
  template:
    metadata:
      labels:
        app: fibonacci
    spec:
      containers:
      - name: fibonacci
        image: reyhanehbarfeh/fibonacci-flask:v.1.0
        resources:
          limits:
            memory: "10M"
            cpu: "10m"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: fibonacci
  name: fibonacci-np
spec:
  type: NodePort
  selector:
    app: fibonacci
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP

    

